title: THE BEST BLOG EVER
email: hxchems1@gmail.com
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: ""
url: "" 
twitter_username: jekyllrb
github_username: Chemslepro

theme: minima
plugins:
  - jekyll-feed



# _config.yml
prose:
  #rooturl: '_posts'  # Default folder to open
  metadata:
    _posts:
      - name: "author"
        field:
          element: "text"
          label: "Pseudo/Blaze"

      - name: "title"
        field:
          element: "text"
          label: "Titre du post"

      - name: "subtitle"
        field:
          element: "text"
          label: "La description"

      - name: "layout"
        field:
          element: "text"
          label: "Quel layout ?"

      - name: "logo"
        field:
          element: "text"
          label: "L'image à afficher à coté du post"


      
  media: "assets/img"  # Folder for uploaded images
  ignore:
    - _site
    - .gitignore
    - README.md
